//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpManagement.Contracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIncentive
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string IncentiveMonth { get; set; }
        public string IncentiveYear { get; set; }
        public int Incentive { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
